# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 027d3bc4c56e74213c67502c7f0e2abb96b7489f38d5b4d99c6354ef2c5fc363625d248cb28c93f333a5075c8dc446547ea2515199e14470943100c0465729b5

test:
  secret_key_base: 15cc1c293fc1e7d9b6e05cee1f962f5711cc910aab4465e0f92b5b8c287bd59731b4bbe238e7810168d0a9bfa584127adf12851cc5c50f204b11d970cfa0981a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
